name: sync fork
on:
  schedule:
    - cron: '*/30 * * * *' # every 30 minutes
  workflow_dispatch: # on button click
    
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - run: ls ${{ github.workspace }}
      - run: cd ${{ github.workspace }} 
      - run: pwd
      - run: git branch
      - run: git branches
      - run: git remote add upstream https://github.com/TheGrayAlien/DemeoMods/
      - run: git fetch upstream
      - run: git fetch --tags upstream
      - run: git checkout origin/DemeoRevolutions
      - run: git log --oneline --graph --decorate --all --date=relative 
      - run: git merge --ff-only upstream/DemeoRevolutions 
      - run: echo "ğŸ This job's status is ${{ job.status }}."
      - run: git log --oneline --graph --decorate --all --date=relative 
